name: flutter_naplo
description: A new Flutter application.

dependencies:
  background_fetch: '^0.1.0'
  path_provider: "^0.4.0"
  fluro: "^1.3.1"
  url_launcher: ^3.0.3
  http: ^0.11.0
  html_unescape: ^1.0.1+2
  flutter_html_view: "^0.3.1"
  http_client: ^0.5.0
  flutter_local_notifications: "0.4.2"
  charts_flutter: ^0.5.0
  dynamic_theme:
    git:
      url: git://github.com/Norbert515/dynamic_theme.git
  flutter_linkify: ^1.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/noise.webp
    - assets/data.json

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Rubik/Rubik-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
    - family: Titillium_Web
      fonts:
        - asset: fonts/Titillium_Web/TitilliumWeb-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
    - family: Material Design Icons
      fonts:
        - asset: fonts/materialdesign/materialdesignicons-webfont.ttf